Lesson16
Grizzy007/NIX12 pull request #11
Opened 2022-07-31 14:36 UTC by Grizzy007

2022-07-31 14:37 UTC, Grizzy007 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Stream API](https://trello.com/c/FKODfn1u/77-stream-api)

2022-07-31 20:30 UTC, Fabolo12 requested changes

2022-07-31 20:30 UTC, Fabolo12 commented on src/main/java/com/nix/lesson10/service/AutoService.java
> +    public boolean IsCarsHave(String detail){
название метода со строчной буквы

2022-07-31 20:30 UTC, Fabolo12 commented on src/main/java/com/nix/lesson10/model/functionals/FunctionImpl.java
> +    public Vehicle toAuto(Map<String, Object> map) {
Сейчас у тебя вышел обычный метод. Если с предикатом я увидел 3 реализации,  то тут совсем не то решение. Должна быть лямбда

2022-08-04 21:19 UTC, Fabolo12 approved these changes

2022-08-05 07:41 UTC, merged