io task done
Grizzy007/NIX12 pull request #12
Opened 2022-08-06 16:09 UTC by Grizzy007

2022-08-06 16:14 UTC, Grizzy007 commented
![](https://github.trello.services/images/mini-trello-icon.png) [IO/NIO](https://trello.com/c/4K8EbFK5/104-io-nio)

2022-08-06 22:04 UTC, Fabolo12 requested changes

2022-08-06 22:04 UTC, Fabolo12 commented on src/main/java/com/nix/lesson10/repository/VehicleFileReader.java
> +            filename = "./src/main/resources/auto.xml";
Чтение файла не верное

2022-08-06 22:04 UTC, Fabolo12 commented on src/main/java/com/nix/lesson10/ui/UserInterface.java
>          System.out.println("Press 7 to exit...");
Тут ошибка с номером выхода, потому что хардкор

2022-08-07 21:33 UTC, Fabolo12 approved these changes

2022-08-07 21:33 UTC, Fabolo12 commented on src/main/java/com/nix/lesson10/ui/UserInterface.java
> +        System.out.println("Press 8 to exit...");
А номер выхода остался хардкодом :)

2022-08-08 06:56 UTC, Grizzy007 commented on src/main/java/com/nix/lesson10/ui/UserInterface.java
> +        System.out.println("Press 8 to exit...");
Оставил чтоб легче было по цифрам ориентироваться

2022-08-08 06:56 UTC, merged